#!/bin/tcsh

############################################################
# Shell script to extract the features of all Aurora-2     #
# training and test data with the advanced ETSI frontend.  #
#                                                          #
# Author: Guenter Hirsch                                   #
# Niederrhein University of Applied Sciences               #
# Date: 13-06-06                                           #
############################################################

#### Define the following pathes ###########################
############################################################
### $SPEECH_ROOT is the root directory of the wave files
### This is the place where you copied the speechdata subdirectory.
set SPEECH_ROOT  = /home/jack/htk/s0/AURORA2
### $REC_DIR is the subdirectory of the recognition SCRIPTS
set REC_DIR      = /home/jack/htk/s0/AURORA2/RECOGNIZER
###########################################################

#### Define the feature extraction executables ##############
#############################################################
### $EXE is the frontend executable
set EXE          = /home/jack/htk/s0/AURORA2/AFE/AdvancedFrontEnd/Linux/bin/AdvFrontEnd
### options for the executable with zeroth cepstral coeff.
set options    = "-q -F RAW -fs 8 -swap"
### $DELTA_EXE is tthe program for determing the Delta and Delta-Deltas
set DELTA_EXE   = /home/jack/htk/s0/AURORA2/AFE/DerivCalc/Linux/bin/derivCalc
set delta_option = "-COMB "
#############################################################

#if ($#argv != 1) then
#        echo ""
#        echo "usage: "$argv[0]" <path to working directory>"
#        echo ""
#        exit
#endif
### $FEAT_ROOT is the root directory of the feature files

set FEAT_ROOT    = /home/jack/htk/s0/AURORA2/FEAT_AFE_14_v1


set test_dirs = ( N1_SNR-5 N1_SNR15 N2_SNR-5 N2_SNR15 N3_SNR-5 N3_SNR15 N4_SNR-5 N4_SNR15 clean1 clean4 N1_SNR0 N1_SNR20 N2_SNR0 N2_SNR20 N3_SNR0 N3_SNR20 N4_SNR0 N4_SNR20 clean2 N1_SNR10 N1_SNR5  N2_SNR10 N2_SNR5 N3_SNR10 N3_SNR5 N4_SNR10 N4_SNR5 clean3 )

set train_dirs = ( N1_SNR10 N1_SNR20 N2_SNR10 N2_SNR20 N3_SNR10 N3_SNR20 N4_SNR10 N4_SNR20 clean1 clean3 N1_SNR15 N1_SNR5 N2_SNR15 N2_SNR5 N3_SNR15 N3_SNR5 N4_SNR15 N4_SNR5 clean2 clean4 )

#goto setc

### create subdirectories for test sets a and b and c
mkdir $FEAT_ROOT
mkdir $FEAT_ROOT/Mfc08TS_seta
mkdir $FEAT_ROOT/Mfc08TS_setb
mkdir $FEAT_ROOT/Mfc08TS_setc
set ndirs = $#test_dirs
while ($ndirs > 0)
	mkdir $FEAT_ROOT/Mfc08TS_seta/$test_dirs[$ndirs]
	mkdir $FEAT_ROOT/Mfc08TS_setb/$test_dirs[$ndirs]
	mkdir $FEAT_ROOT/Mfc08TS_setc/$test_dirs[$ndirs]
	@ ndirs--
end
### create subdirectories for multicondition training
mkdir $FEAT_ROOT/Mfc08_multiTR
set ndirs = $#train_dirs
while ($ndirs > 0)
	mkdir $FEAT_ROOT/Mfc08_multiTR/$train_dirs[$ndirs]
	@ ndirs--
end
### create subdirectory for clean training
mkdir $FEAT_ROOT/Mfc08_cleanTR

### perform feature extraction for multicondition training data
set list_file   = $REC_DIR{/SCRIPTS/MULTITR08_HCOPY.SCP}
set in_files   = `awk '{print $1}' $list_file`
set out_files  = `awk '{print $2}' $list_file`
if (-e /tmp/tmpau2.mfc) then
        rm /tmp/tmpau2.mfc
endif
if (-e /tmp/tmpau2.vad) then
        rm /tmp/tmpau2.vad
endif
set nfiles     = $#in_files
while ($nfiles > 0)
#	$EXE $options $SPEECH_ROOT/$in_files[$nfiles] /tmp/tmpau2.mfc
        $EXE $options $SPEECH_ROOT/$in_files[$nfiles] $FEAT_ROOT/$out_files[$nfiles]
#	$DELTA_EXE $delta_option /tmp/tmpau2.mfc $FEAT_ROOT/$out_files[$nfiles] /tmp/tmpau2.vad
#        $DELTA_EXE $delta_option /tmp/tmpau2.mfc $FEAT_ROOT/$out_files[$nfiles]
#        rm /tmp/tmpau2.mfc /tmp/tmpau2.vad
	@ nfiles--
end

### perform feature extraction for clean training data
set list_file   = $REC_DIR{/SCRIPTS/CLEANTR08_HCOPY.SCP}
set in_files   = `awk '{print $1}' $list_file`
set out_files  = `awk '{print $2}' $list_file`
set nfiles     = $#in_files
while ($nfiles > 0)
#	$EXE $options $SPEECH_ROOT/$in_files[$nfiles] /tmp/tmpau2.mfc
        $EXE $options $SPEECH_ROOT/$in_files[$nfiles] $FEAT_ROOT/$out_files[$nfiles]
#	$DELTA_EXE $delta_option /tmp/tmpau2.mfc $FEAT_ROOT/$out_files[$nfiles] /tmp/tmpau2.vad
#        $DELTA_EXE $delta_option /tmp/tmpau2.mfc $FEAT_ROOT/$out_files[$nfiles]
#        rm /tmp/tmpau2.mfc /tmp/tmpau2.vad
	@ nfiles--
end

### perform feature extraction for test set a data
set list_file   = $REC_DIR{/SCRIPTS/TSA08_HCOPY.SCP}
set in_files   = `awk '{print $1}' $list_file`
set out_files  = `awk '{print $2}' $list_file`
set nfiles     = $#in_files
set count = 1
while ($count <= $nfiles)
#	$EXE $options $SPEECH_ROOT/$in_files[$nfiles] /tmp/tmpau2.mfc
        $EXE $options $SPEECH_ROOT/$in_files[$nfiles] $FEAT_ROOT/$out_files[$nfiles]
#	$DELTA_EXE $delta_option /tmp/tmpau2.mfc $FEAT_ROOT/$out_files[$nfiles] /tmp/tmpau2.vad
#        $DELTA_EXE $delta_option /tmp/tmpau2.mfc $FEAT_ROOT/$out_files[$nfiles]
#        rm /tmp/tmpau2.mfc /tmp/tmpau2.vad
	@ nfiles--
end

setb:
### perform feature extraction for test set b data
set list_file   = $REC_DIR{/SCRIPTS/TSB08_HCOPY.SCP}
set in_files   = `awk '{print $1}' $list_file`
set out_files  = `awk '{print $2}' $list_file`
set nfiles     = $#in_files
set count = 1
while ($count <= $nfiles)
#	$EXE $options $SPEECH_ROOT/$in_files[$nfiles] /tmp/tmpau2.mfc
        $EXE $options $SPEECH_ROOT/$in_files[$nfiles] $FEAT_ROOT/$out_files[$nfiles]
#	$DELTA_EXE $delta_option /tmp/tmpau2.mfc $FEAT_ROOT/$out_files[$nfiles] /tmp/tmpau2.vad
#        $DELTA_EXE $delta_option /tmp/tmpau2.mfc $FEAT_ROOT/$out_files[$nfiles]
#        rm /tmp/tmpau2.mfc /tmp/tmpau2.vad
	@ nfiles--
end

setc:
### perform feature extraction for test set c data
set list_file   = $REC_DIR{/SCRIPTS/TSC08_HCOPY.SCP}
set in_files   = `awk '{print $1}' $list_file`
set out_files  = `awk '{print $2}' $list_file`
set nfiles     = $#in_files
set count = 1
while ($count <= $nfiles)
#	$EXE $options $SPEECH_ROOT/$in_files[$nfiles] /tmp/tmpau2.mfc
        $EXE $options $SPEECH_ROOT/$in_files[$nfiles] $FEAT_ROOT/$out_files[$nfiles]
#	$DELTA_EXE $delta_option /tmp/tmpau2.mfc $FEAT_ROOT/$out_files[$nfiles] /tmp/tmpau2.vad
#        $DELTA_EXE $delta_option /tmp/tmpau2.mfc $FEAT_ROOT/$out_files[$nfiles]
#        rm /tmp/tmpau2.mfc /tmp/tmpau2.vad
	@ nfiles--
	@ nfiles--
end

